2019-10-30 11:06:07,650-case11-INFO-测试开始啦-[logger.py:80]
2019-10-30 11:06:07,650-case11-ERROR-测试报错了-[logger.py:81]
2019-10-30 11:06:07,650-case11-INFO-测试结束-[logger.py:83]
2019-10-30 11:07:38,932-case-INFO-测试开始啦-[logger.py:80]
2019-10-30 11:07:38,932-case-ERROR-测试报错了-[logger.py:81]
2019-10-30 11:07:38,932-case-INFO-测试结束-[logger.py:83]
2019-10-30 11:07:45,836-case-INFO-测试开始啦-[logger.py:80]
2019-10-30 11:07:45,836-case-ERROR-测试报错了-[logger.py:81]
2019-10-30 11:07:45,836-case-INFO-测试结束-[logger.py:83]
